### PR TITLE
chore(ci): update metal delete action to use sustainable-computing-io fork

### PR DESCRIPTION
**Pull request by vprashar2929**
This commit updates metal delete action in our CI to use the forked version maintained under sustainable-computing-io organization.

### CODE REVIEW

**Comment by KaiyiLiu1234** [comment]
First glance we need to change how we delete servers because runnerName is not an acceptable input for https://github.com/equinix-labs/metal-sweeper-action. The inclusion of the **runnerName** was rootfs change on his fork: https://github.com/rootfs/metal-delete-action.

**Review by KaiyiLiu1234 — CHANGES_REQUESTED** [review]
Either we do not clean based on runner name or we continue using rootfs/metal-delete-action

**Comment by vprashar2929** [comment]
My bad I should have mentioned it in the description 😞  I have ported humanin's changes in his fork to the `sustainable-computing-io` org fork: https://github.com/sustainable-computing-io/metal-sweeper-action/commits/main/

**Comment by KaiyiLiu1234** [comment]
Oh you are right! I did not notice that it was merged.

**Review by KaiyiLiu1234 — APPROVED** [review]

**Pull request merged**
