### PR TITLE
remove host-passthrough on vm to emulate public cloud

### PR DESCRIPTION
**Pull request by sthaha**

### CODE REVIEW

**Comment by vimalk78** [comment]
perhaps we need to specify which CPU is being emulated if cpu pass through is disabled.

**Comment by sthaha** [comment]
@aharivel any thoughts on this? What we are trying to achieve here is to create VM that close to what you would find on public clouds.

**Comment by aharivel** [comment]
CPU host pass-through passes the host CPU model features, model, stepping, exactly to the guest. 
So this make sens when you don't have to worry about the  x86_64 architecture ABI compatibility level.
Now if you want to fix the CPU architecture because you want to have the same ABI for your VM when you migrate it from one server to another (like from Intel to AMD server) then you should fix it to a Named model (Cascadelake-Server, Skylake-Server-IBRS-noTSX,...)

But if you want an answer to your question, we need to answer those one before: what are the Hypervisor used in Public Cloud? And what are the CPU set-up? Emulated, Pass-Throught, Hybrid ?...
Because If I'm not mistaken, for example, the underlying Hypervisor for Amazon EC2 (Elastic Compute Cloud) are both d. Xen and e. Nitro.

**Comment by sthaha** [comment]
@aharivel Any thoughts on this? What we trying to achieve here is to create a creat

**Pull request closed without merging**
