### PR TITLE
chore(ansible): refactor kvm_vm role

### PR DESCRIPTION
**Pull request by vprashar2929**
This commit refactors the kvm_vm role with the following changes:
- Moved the `cloud-init-script.sh` file to `kvm_vm/files` directory to better organize role-specific files.
- Replaced module calls with Fully Qualified Collection Names (FQCNs) for easier linking to the modules.
- Relocated the variables previously defined in `defaults` to the `vars` directory, reflecting their less frequent changes.
- Removed the workflow step that copies the `cloud-init-script.sh` and meta-data files to `/tmp` directory and integrated this as a task within the `kvm_vm` role for improved handling.
- Added a README.md file to provide documentation for the `kvm_vm` role.

### CODE REVIEW

**Comment by rootfs** [comment]
@vprashar2929 do you have a good run with this change? feel free to merge it if no error happens.

**Comment by vprashar2929** [comment]
Sample CI run:
Kepler with model server: https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/10908634793
Standalone Kepler: https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/10908633639

**Comment by KaiyiLiu1234** [comment]
@vprashar2929 Sorry about the dependabot push. I noticed an error the Validation with Model Server and wanted to see if this ref-kvm encountered the same error. It worked instead so this PR might fix the current issue with the Validation with Model Server on main.

**Comment by KaiyiLiu1234** [comment]
Feel free to remove the files. I can also do that in the morning.

**Comment by vprashar2929** [comment]
@KaiyiLiu1234 I think the [error](https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/10931417709/job/30346637072#step:2:38) might be related to creation of runner on equinix end 🤔

**Comment by KaiyiLiu1234** [comment]
@vprashar2929 Shouldn't be. validation with model server and validation with standalone kepler both use the same create runner reusable workflow. I will double check though.

**Pull request merged**
