### PR TITLE
as kepler action support Tekton update code accordingly

### PR DESCRIPTION
**Pull request by SamYuan1990**
as kepler action support Tekton update code accordingly

### CODE REVIEW

**Comment by SamYuan1990** [comment]
ref https://github.com/sustainable-computing-io/kepler-action/actions/runs/9918634973/job/27403522368#step:3:619

**Comment by SamYuan1990** [comment]
ref to https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/9927550342/job/27422710496?pr=61#step:12:233 I suppose the kepler and prometheus settings are collect. but not sure if kepler helm deployment with correct parameters.

**Comment by SamYuan1990** [comment]
even if https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/9927691365/job/27423041991?pr=61#step:12:219 the prometheus checking passed, the final output still empty. @rootfs could you please check?

**Comment by KaiyiLiu1234** [comment]
This would be helpful for the model trainer as I won't have to worry about install tekton beforehand. I can remove that line of code responsible for that.

**Comment by KaiyiLiu1234** [comment]
LGTM

**Review by KaiyiLiu1234 — APPROVED** [review]

**Pull request merged**
