### PR TITLE
[fix]: add missing env for estimator service

### LINKED ISSUE #331: Validation with Model Sever fails due to Estimator
Estimator is encountering an error with being started which breaks the validation with model server

### PR DESCRIPTION
**Pull request by SamYuan1990**
fix #331
add missing env for estimator service.

### CODE REVIEW

**Comment by SamYuan1990** [comment]
@rootfs , @KaiyiLiu1234 
I make a test for this PR at https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/12308750130/job/34354732457, do you know how to update ansible playbook cfg to make ansible running with handler functions been enabled and invoked?

**Comment by KaiyiLiu1234** [comment]
I do not think we use any handlers. We can use handler keyword if you want to add handler functions.

**Comment by SamYuan1990** [comment]
> I do not think we use any handlers. We can use handler keyword if you want to add handler functions.

https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/12309072904/job/34355663300#step:6:5
emmmm, it seems the service is not been installed correctly?

**Comment by SamYuan1990** [comment]
https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/12310123263/job/34358353362
the service description file is not loaded correctly. @KaiyiLiu1234 , could you please help check?

**Comment by SamYuan1990** [comment]
@KaiyiLiu1234 , @sunya-ch 
I suppose we can fix it by providing a model-server image as env vars. for example I had tested https://github.com/sustainable-computing-io/kepler-metal-ci/actions/runs/12310368453/job/34358972760 and the env value for model server image can make the process works.
but... what value of image tag we should given here?

**Comment by KaiyiLiu1234** [comment]
Model Server and estimator is deployed in my-vm. You should not be able to access the logs of the estimator service from the workflow. Interesting that the image wasn't loaded properly in the playbook. I guess it was not updated. Great find!

**Review by KaiyiLiu1234 — APPROVED** [review]
lgtm

**Pull request merged**
