### PR TITLE
try to integrate with kepler action

### PR DESCRIPTION
**Pull request by SamYuan1990**
with https://github.com/sustainable-computing-io/kepler-action/pull/126 kepler-action supports for existing k8s cluster by Equinix, use this PR for integration.

### CODE REVIEW

**Comment by SamYuan1990** [comment]
@rootfs , could you please help test this PR?

**Comment by rootfs** [comment]
@SamYuan1990 i fixed a couple things here https://github.com/sustainable-computing-io/kepler-metal-ci/commit/75de9640db8e3facaeca200710a48cc56d9b9ada

**Comment by SamYuan1990** [comment]
> @SamYuan1990 i fixed a couple things here [75de964](https://github.com/sustainable-computing-io/kepler-metal-ci/commit/75de9640db8e3facaeca200710a48cc56d9b9ada)

I suppose it seems won't work.
btw,
- how we shutdown/destroy Equinix k8s cluster with github action?
- how we upload a dev image on Equinix k8s cluster?

**Comment by SamYuan1990** [comment]
merge as it is.

**Pull request merged**
